[lint]
# Exclude specific files or directories from linting
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "instance",
    "migrations",
    "node_modules",
    "app/utils/text_processing.py",  # Excluding this file from linting checks
]

# Specify which rules to ignore globally
ignore = ["E203"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__ files
