[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "W", "I", "B", "C4", "ARG", "SIM"]
ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "instance",
]

[tool.ruff.isort]
known-first-party = ["app"]
