[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "C4", "ARG", "SIM", "N", "D"]
ignore = [
    "E203",  # Whitespace before ':'
    "E226",  # Missing whitespace around arithmetic operator
    "E302",  # Expected 2 blank lines
    "E305",  # Expected 2 blank lines after class or function definition
    "E501",  # Line too long
    "W292",  # No newline at end of file
    "W293",  # Blank line contains whitespace
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D107",  # Missing docstring in __init__
    "C901",  # Function is too complex
]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "instance",
    "migrations",
    "node_modules",
]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "double"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
